name: IP Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get IP
        run: |
          curl https://api.ipify.org

      # Ajoutez d'autres étapes de votre workflow ici
